### ISSUE TITLE
net standard version2.0

### ISSUE THREAD

**Issue by rbarker8** [Azure/App-Service-Migration-Assistant#12]
Hi when running the preview of the migration tool I see the attached error instead of being able to select a site, if i run the GA tool it works, but i have Virtual Directories i would like to migrate, thanks.

#### Investigative information

Please provide the following:

- UTC Timestamp: 
- Migration Tool App version : Preview
- OS Version: 2012R2

#### Repro steps

Just open the app
-->

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

See attached

![appmigprev](https://user-images.githubusercontent.com/28595488/64175378-17e4f880-ce53-11e9-81a9-a4ce46c0bdd5.PNG)

**Comment by wadeh-ms** [comment]
Hi,

This error is happening very early in the process.  Essentially, we are not able to load our assemblies.  At this time, we suspect that this might be an issue with the version of the .NET framework installed on your machine.

The Migration Assistant has a dependency on version 3.5 of the .NET Framework.  Can you please let us know which version, or versions, of the Framework are installed?

Thanks,
-Wade

**Comment by krolson** [comment]
The latest version (1.0.1) of Migration Assistant should no longer have issues due to different installed .NET framework versions. Please try the latest build and let us know if you still see this type of issue.
Closing this item for now since there has been no response - but please open a new issue if this is still happening for you.
