### ISSUE TITLE
Cannot login to Azure on 2008 R2

### ISSUE THREAD

**Issue by spaelling** [Azure/App-Service-Migration-Assistant#16]
Unable to login to Azure, the button is greyed out.

![image](https://user-images.githubusercontent.com/871412/68396549-06c9a800-0172-11ea-92d9-32672c9efd3c.png)

#### Investigative information

Please provide the following:

- UTC Timestamp:
- Migration Tool App version : 0.0.7
- OS Version: 2008 R2

#### Repro steps

try to migrate a site

#### Expected behavior

Able to login to Azure

#### Actual behavior

Not able to login to Azure

#### Known workarounds

Unknown

**Comment by krolson** [comment]
Thank you for reporting this @spaelling 

I believe this is likely due to issues with making outbound requests, and have opened a bug to improve the behavior here to give an actionable message in this case as well as to update wiki documentation to give more details up front on why this is needed. I see you're using version 0.0.7, but version 1.0.0 (just released) will similarly fail without outbound connectivity - notably it will fail during the site assessment.

App Service Migration Assistant needs to make outgoing requests to do the following things:

- Get a login token for the user's Azure account (actual log-in can be done on another machine)
- Call Azure resource manager APIs (to show settings options and create target Azure migration resources)
- Complete the site assessment (calls assessment API that returns assessment information based on anonymized configuration information) - this is new in v1.0.0 as assessment in 0.0.7 worked differently
- (Optionally) Anonymized logging (to help us improve the tool)
- Publish the site content to the new Azure site during migration

Could you confirm that the server where you are using the tool is allowing outbound traffic or are you able to try enabling it?

We apologize for the inconvenience. Please let me know if you need more information on this and/or if you need more information to enable outbound requests, such as the target endpoints.

**Comment by spaelling** [comment]
Where can I get v.1.0.0? I downloaded from [appmigration.microsoft.com/readiness](https://appmigration.microsoft.com/readiness) and from what I can tell that is v0.0.7 - and what version is the preview? 1.0.0+?

I will try and check up on any outbound connections being blocked. There should not be, but there may be some weird firewall configurations. If there is I should be able to allow the traffic.

Any clue when the assistant will be able to migrate to existing service plans? I need to migrate all the sites to an app service environment, so I can currently only use the tool to asses if a migration will be successful or not. It would make my life so much easier, and if it is in a near future, I can postpone the migration project a bit.

**Comment by krolson** [comment]
We just updated the appmigration.microsoft.com/readiness page with the v1.0.0 just last evening, so if you go today you should see a single download option and that will be v1.0.0 (previously this page had both version 0.0.7 and Preview version 0.1.2). Please let me know if you are not seeing or not able to download the newer version!

I am also delighted to tell you that one of the new features in the v1.0.0 release is the ability to migrate to an existing App Service Plan (ASP) rather than always creating a new one. Earlier versions of the assistant would allow you to migrate to a v2 App Service Environment (ASE) - however in previous versions this would have been limited to ASEv2 (i.e. not older v1 ASEs) and would have required creating a new App Service Plan on the ASE. There are some notes on major changes between versions here: https://github.com/Azure/App-Service-Migration-Assistant/wiki/Release-Notes.

**Comment by spaelling** [comment]
Now using 1.0 which is bringing other challenges. So closing this for now. Thanks for the help.
