### ISSUE TITLE
option to migrate despite errors

### ISSUE THREAD

**Issue by spaelling** [Azure/App-Service-Migration-Assistant#26]
Something like the authentication type being WindowsAuthentication should not block the migration. For production it is not an option to disable this without a service window. Using something else like AAD auth in the web app would also require some code changes which one possibly will want to do on the migrated app.

Would be great if it is an option to "continue at own risk"

**Comment by wadeh-ms** [comment]
Hello,

Thanks for your suggestion to allow a migration with known errors.

At this time, the Migration Assistant is intended to do a “lift and shift” of sites that can run unmodified under Azure App Service.  In the case where a site has known incompatibilities with the service, it should provide sufficient information so that the site administrator can address the issues before migration.

We’ve discussed the possibility of migrating known incompatible sites among the team a number of times, but feel that it is outside of the current scope.  That said, we do revisit this topic periodically, and your feedback is important to help us weigh the decision against other work that we are doing to the Migration Assistant.

Thanks again,
-Wade

**Comment by spaelling** [comment]
> At this time, the Migration Assistant is intended to do a “lift and shift” of sites that can run unmodified under Azure App Service.  In the case where a site has known incompatibilities with the service, it should provide sufficient information so that the site administrator can address the issues before migration.

That just severely limits the number of sites that is possible to migrate. My experience thus far is that lots and lots of sites use WindowsAuthentication, and in many cases simply to limit who can access the site, not necessarily using the token to identify the user.
I also often get an incombatability from location tags, which I do not understand exactly what is, but enough to not removing them in a production environment.

What I have done to use the migration tool is to export sites and import on a different VM with IIS installed. I am then free to change settings for a site to make it compatible. But in many cases it would be just ok to migrate an incombatible site and make a minor change once running in Azure.

I hope you will reconsider you stance, perhaps make it a switch when you run the migration tool, so that it is a very intentional use to ignore errors and migrate anyways.

**Comment by krolson** [comment]
The ability to package (and migrate) a site even with a failed configuration check is now possible using the PowerShell scripts option (use "-MigrateSitesWithIssues" flag on Get-SitePackage.ps1 script) - the scripts are a lightweight option that involves simply dropping a directory of scripts on the machine (or at least a machine-accessible location) in order to try it out.

Main info page: https://github.com/Azure/App-Service-Migration-Assistant/wiki/PowerShell-Scripts
Place to download: https://azure.microsoft.com/en-us/services/app-service/migration-assistant/
