### ISSUE TITLE
unable to start the assessment tool 

### ISSUE THREAD

**Issue by dakouka** [Azure/App-Service-Migration-Assistant#3]
After Starting the program on the iis server 
nothing happens shows 0 Site found .
and it is not possible to start the assessment .
all the options are disabled , and the list of the web site is empty
![p1](https://user-images.githubusercontent.com/30494167/54189063-b0f51100-44b9-11e9-9ba1-b8a15e7b4bc3.PNG)

this issue prevents us to continue the migration of our web applications to the azure 

 

#### Investigative information

Please provide the following:

- UTC Timestamp:09:19
- Migration Tool App version :latest version
- OS Version: windows 2012 

#### Repro steps
download , install the App Service Migration tool (preview) 
run the program as Administrator 

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

**Comment by krolson** [comment]
Thanks for reporting this!
To help figure out what's going on could you please do the following:

0. Confirm if you saw this after using the desktop shortcut (i.e. not just on the very first time the app starts automatically as part of the installation : we've seen this happen sometimes where the app starts as part of the install but the related references don't seem to be accessible yet and just starting it again works fine - we'd like to know if that happened to you.)

1. Find out the path for the installation

- Right-click the AppServiceMigrationTool desktop shortcut and select Properties. Let us know what the value looks like for the "Start in" value (should be something like: C:\Users\krolson\AppData\Local\Programs\azure-appService-migrationtool\). Notably if you have a space in your username please let us know the product version on the AppServiceMigrationTool.exe (right-click the .exe > Properties > Details)

2. Try running the related get-sites-information command directly 

- Go to the install location you found in (1) - you should have a directory there called "migcheckbin". Using an administrator command prompt navigate to that folder and run "migcheck.exe listsites" and let us know the output - this is exactly what the App Service Migration Tool should be doing to populate a site selection list for you in the UI and could help us identify where the issue is happening.

**Comment by panchagnula** [comment]
@dakouka I have seen this behavior on the first launch of the tool at times - what happens if you close & restart the tool, does the issue persist? If it still does then please do share the info posted by Kristina above. Thank you!

**Comment by dakouka** [comment]
Thanks @krolson  & @panchagnula 
the issue pressist also when I tried to lunch from the installation directory .
but the good news is that after upgrade to the new release this behaviour disapear and now the programs is Analyzing the IIS configuration 
B U T ... there is an annoying bug - the tool is failed on a duplicate key in collection,
the error : 
**Unhandled Exception: System.ArgumentException: An item with the same key has already been added. Key: default web site\c:\program files\MyWs\Ws1
 at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
 at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
 at migcheck.BuildApplicationMap.InitializePathToApplicationMapper(Site Site) in D:\a\1\s\src\MigrationTool\migcheck\BuildApplicationMap.cs:line 22
 at migcheck.BuildSiteMap.InitializeSite(Site Site) in D:\a\1\s\src\MigrationTool\migcheck\BuildSiteMap.cs:line 144
 at migcheck.BuildServerMap.InitializeServerMap() in D:\a\1\s\src\MigrationTool\migcheck\BuildServerMap.cs:line 82
 at migcheck.Program.Main(String[] args) in D:\a\1\s\src\MigrationTool\migcheck\Program.cs:line 101**

 My assumption is that the app is building a collection bases on the web apps in the IIS and the key of the collection is the physical directory path.
It's happens because in our case there are few web applications  that points to the same physical path .when I remove all Duplicates this  behavior disappear .

**Comment by wadeh-ms** [comment]
Thanks for the report, @dakouka.

Your assumption is correct.  In the current version of the migration tool, there are some cases where it's necessary to derive the application from a physical path.  This code will fail if there are multiple applications pointing to the same physical path.

Unfortunately, in the short term, I suspect that I will need to detect this and flag it as a disqualifying condition for an automatic migration.  In the long term, I am working on a different mechanism for analyzing an on-premises installation that will be more robust and handle many more scenarios like this one.

-Wade

**Comment by simondick** [comment]
@wadeh-ms I am also getting the same error as @dadouka above, but for default ftp site, but on looking at the paths to all the sites there not 2 with the same path. Is there any other reason it could be picking up this duplicate?

**Comment by NitashaV** [comment]
We have released a [new Preview version](https://appmigration.microsoft.com/readiness) of Migration Assistant today that should help address this class of issues. We would appreciate if you gave this update (in Preview) a try and let us know if this works for your scenario. Thanks

**Comment by Gouravkala** [comment]
Hi , is there way if we can run the App-server-migration-Assistant from commandline/powershell ?

**Comment by krolson** [comment]
Hi @Gouravkala,

You can run part of the migration assistant from commandline, as least to do discovery of sites and single-site assessment (not migration). Check out the notes here: https://github.com/Azure/App-Service-Migration-Assistant/wiki/How-the-Assistant-Works#what-information-is-sent-for-assessments . This outlines where to find and how to use the iisConfigAssistant.exe to get the list of sites and generate an AssessmentInfo.json file. If using the latest version of Migration Assistant you should be able to also get single-site readiness results by running commands similar to below (change the site name and file locations as needed) - note this uses a simplified version of the GetSiteAssessmentData command that produces an assessmentinfo.json file that may contain sensitive server data, since it's just to use locally:

```
iisConfigAssistant.exe GetSiteAssessmentData "Default Web Site" false > C:\TEMP\NonAnonAssessmentInfo.json
iisConfigAssistant.exe AssessReadiness C:\TEMP\NonAnonAssessmentInfo.json > C:\TEMP\AssessmentResults.json
```

PowerShell scripts is something we have in the works.

Thanks,
Kristina

**Comment by Gouravkala** [comment]
Thanks you for your reply. if I understand we cant run the app migration assistant  script/tool from a centralized server we have to run the same from inside the webserver only as it detects the running websites on the server.

**Comment by krolson** [comment]
That's correct - the current Migration Assistant must run locally on the server that is being assessed.
