### ISSUE TITLE
App migration tool goes blank with no error message

### ISSUE THREAD

**Issue by gilbertsak** [Azure/App-Service-Migration-Assistant#31]
Hey I just see a blank screen after going through the steps and choosing skip database connections. 
Does anyone have an idea of what is happening? if not where can I see if there if there is an error message in the background? 

- UTC Timestamp: 14:00 
- Migration Tool App version :1.0.2
- OS Version: Windows Server 2012 R2

1. Prompted me to choose website App from IIS
2. It automatically checked if the app was ok. Everything pass apart from-> 1 warning (local database)
3. Started migration process. Was going through the process then just went blank. 

![AzureAppMigration showing empty space](https://user-images.githubusercontent.com/48216893/79764338-2538ef80-831d-11ea-97ed-ba97b6118521.png)

**Comment by gilbertsak** [comment]
It shows the following before going blank: 
![AzureAppMigration showing empty space](https://user-images.githubusercontent.com/48216893/79863796-44dd2000-83d0-11ea-8b68-99c5785ead6b.png)

I do see the web application files when i FTP in though in Azure portal, not sure if all the files are present. Currently in the process of trying to connect it to a managed instance to see if it will work

**Comment by ESSystems** [comment]
Same issue here. Starts the migration then the below. OS Server 2012 R2

![image](https://user-images.githubusercontent.com/25923535/79875405-8629fb80-83e1-11ea-8094-6cd93fa05922.png)

**Comment by krolson** [comment]
Thank you for letting us know this is happening!

@gilbertsak Is that happening for you consistently (i.e. you have attempted a migration more than once, and it has occurred each time)? If you have attempted migrations for other sites and these have worked without hitting this issue please let us know. Would you be willing to share your site name with us for us to try to look up additional traces? You could send it to appmigratetalk@microsoft.com if you'd rather not post it

@ESSystems Would you be willing to share your site name with us (email to appmigratetalk@microsoft.com if you'd rather not post it) as well as the approximate time that this issue occurred for you? 

We'll look into this and see if we can figure it out.

**Comment by krolson** [comment]
If you run into this issue, could you please tell us the following details / try a command and let us know what happens? This information may help us to reproduce/target this issue.

- Tell us approximately how long did it show the “Publishing site content (step 2 of 3)” before it transitioned to a blank view? 

- Try manually creating the .zip of the site content as the tool is trying to do and let us know what happens (i.e. command output and if the .zip is created in the specified path, also if it takes a long time)? You can do this by using an admin command prompt and running a command like below (change [username] to your user name and make sure [siteName] is exactly the same capitalization as you get returned from the “iisConfigAssistant.exe GetSiteList” command – the path to the .exe is based on typical install location, but if iisConfigAssistant isn’t there you can double-check the path by right-clicking the desktop shortcut icon and checking the Properties>Start In value): 

`c:\Users\[username]\AppData\Local\Programs\azure-appService-migrationAssistant\iisConfigAssistant\iisConfigAssistant.exe GetZippedSiteContent "[siteName]" "C:\Users\[username]\AppData\Local\Temp\[siteName]_1234567890123.zip"`

- When checking for the created .zip could you also let us know if you see a .zip sitting there from one of the migrations that did not complete – it would be in the same temp folder with name format [sitename]_[number].zip from the time that the migration failed?

**Comment by gilbertsak** [comment]
Hey all,

I decided not to use the migration assistant and used zip deploy in scm which didn’t took roughly about 7 minutes. I did not see any uploaded files from the migration assistant in the azure web app directory. Using the migration assistant in the past I have left it for many hours. I think it must be our work internal firewalls blocking the upload. Thank you for the help.

Regards,

Gilbert

**Comment by ajgball** [comment]
Command Line Fails with [11:38] matthew.nicholson@optiogroup.com
    
C:\Windows\system32>c:\Users\admin\AppData\Local\Programs\azure-appService-migrationAssistant\iisConfigAssistant\iisConfigAssistant.exe GetZippedSiteContent "staging.optiogroup.co.uk" "C:\Users\admin\AppData\Local\Temp\staging-optiogroup_1234567890123.zip"
{
  "HResult": "80131502",
  "DisplayMessage": "Index was out of range. Must be non-negative and less than the size of the collection.\r\nParameter name: index",
  "TelemetryMessage": "An unhandled exception occurred.  HResult=80131502",
  "StackTrace": "   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()\r\n   at System.Collections.Generic.List`1.get_Item(Int32 index)\r\n   at iisFrameworkDetector.FrameworkDetector.InitializeFrameworkDetector(IisConfiguration iisConfig) in d:\\a\\1\\s\\src\\IisConfigurationHelper\\iisFrameworkDetector\\FrameworkDetector.cs:line 59\r\n   at iisFrameworkDetector.FrameworkDetector..ctor(String SerializedConfiguration) in d:\\a\\1\\s\\src\\IisConfigurationHelper\\iisFrameworkDetector\\FrameworkDetector.cs:line 38\r\n   at iisMigrationHelper.IisMigrationHelper.GetZippedSiteContent(String SiteName, String OutputFile) in d:\\a\\1\\s\\src\\IisConfigurationHelper\\iisMigrationHelper\\IisMigrationHelper.cs:line 394\r\n   at iisConfigAssistant.Program.DoGetZippedSiteContent(String[] args) in d:\\a\\1\\s\\src\\IisConfigurationHelper\\iisConfigAssistant\\Program.cs:line 360\r\n   at iisConfigAssistant.Program.Main(String[] args) in d:\\a\\1\\s\\src\\IisConfigurationHelper\\iisConfigAssistant\\Program.cs:line 60"

**Comment by ajgball** [comment]
Command Line Fails with - 
    
C:\Windows\system32>c:\Users\admin\AppData\Local\Programs\azure-appService-migrationAssistant\iisConfigAssistant\iisConfigAssistant.exe GetZippedSiteContent "staging.xxxxgroup.co.uk" "C:\Users\admin\AppData\Local\Temp\staging-optiogroup_1234567890123.zip"
{
  "HResult": "80131502",
  "DisplayMessage": "Index was out of range. Must be non-negative and less than the size of the collection.\r\nParameter name: index",
  "TelemetryMessage": "An unhandled exception occurred.  HResult=80131502",
  "StackTrace": "   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()\r\n   at System.Collections.Generic.List`1.get_Item(Int32 index)\r\n   at iisFrameworkDetector.FrameworkDetector.InitializeFrameworkDetector(IisConfiguration iisConfig) in d:\\a\\1\\s\\src\\IisConfigurationHelper\\iisFrameworkDetector\\FrameworkDetector.cs:line 59\r\n   at iisFrameworkDetector.FrameworkDetector..ctor(String SerializedConfiguration) in d:\\a\\1\\s\\src\\IisConfigurationHelper\\iisFrameworkDetector\\FrameworkDetector.cs:line 38\r\n   at iisMigrationHelper.IisMigrationHelper.GetZippedSiteContent(String SiteName, String OutputFile) in d:\\a\\1\\s\\src\\IisConfigurationHelper\\iisMigrationHelper\\IisMigrationHelper.cs:line 394\r\n   at iisConfigAssistant.Program.DoGetZippedSiteContent(String[] args) in d:\\a\\1\\s\\src\\IisConfigurationHelper\\iisConfigAssistant\\Program.cs:line 360\r\n   at iisConfigAssistant.Program.Main(String[] args) in d:\\a\\1\\s\\src\\IisConfigurationHelper\\iisConfigAssistant\\Program.cs:line 60"

**Comment by ajgball** [comment]
Command line fails with : - C:\Windows\system32>c:\Users\admin\AppData\Local\Programs\azure-appService-migrationAssistant\iisConfigAssistant\iisConfigAssistant.exe GetZippedSiteContent "staging.xxxxxgroup.co.uk" "C:\Users\admin\AppData\Local\Temp\staging-xxxxxxgroup_1234567890123.zip"
{
  "HResult": "80131502",
  "DisplayMessage": "Index was out of range. Must be non-negative and less than the size of the collection.\r\nParameter name: index",
  "TelemetryMessage": "An unhandled exception occurred.  HResult=80131502",
  "StackTrace": "   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()\r\n   at System.Collections.Generic.List`1.get_Item(Int32 index)\r\n   at iisFrameworkDetector.FrameworkDetector.InitializeFrameworkDetector(IisConfiguration iisConfig) in d:\\a\\1\\s\\src\\IisConfigurationHelper\\iisFrameworkDetector\\FrameworkDetector.cs:line 59\r\n   at iisFrameworkDetector.FrameworkDetector..ctor(String SerializedConfiguration) in d:\\a\\1\\s\\src\\IisConfigurationHelper\\iisFrameworkDetector\\FrameworkDetector.cs:line 38\r\n   at iisMigrationHelper.IisMigrationHelper.GetZippedSiteContent(String SiteName, String OutputFile) in d:\\a\\1\\s\\src\\IisConfigurationHelper\\iisMigrationHelper\\IisMigrationHelper.cs:line 394\r\n   at iisConfigAssistant.Program.DoGetZippedSiteContent(String[] args) in d:\\a\\1\\s\\src\\IisConfigurationHelper\\iisConfigAssistant\\Program.cs:line 360\r\n   at iisConfigAssistant.Program.Main(String[] args) in d:\\a\\1\\s\\src\\IisConfigurationHelper\\iisConfigAssistant\\Program.cs:line 60"

**Comment by krolson** [comment]
For anyone encountering this issue please let us know the time that it happened and the sitename you used as your target. The sitename could be sent to us at appmigratetalk@microsoft.com if you'd rather not post it.

@gilbertsak : Thank you for letting us know what happened. I'm sorry that you ran into this issue, but at least glad to hear you were able to move your site content manually. The detail that it can site for hours and that there might be firewall complications gives us something to look into more.

@ajgball : Thank you for posting these extra details. Knowing that the zip is there from a previous migration helps us isolate where the issue occurred - after the zip creation - which means the command you ran manually should have worked (the error you posted is usually from typing in the sitename with different casing from how it is returned in the GetSiteList command - it is very case sensitive). While we do not yet have a repro of this issue - you could at least complete the migration using the .zip left in the Temp location from the failed migration (or from manually running the GetZippedSiteContent command assuming casing is the only issue) using these steps:
1. Go to the "scm" for the site you created during the migration: YourSiteName.scm.azurewebsites.net
2. Click on "Debug Console" and choose either the CMD or PowerShell option to get to the file content view
3. You should see 2 folders listed: "LogFiles" and "Site". Drag the .zip file over the folders list in the browser and a blue square should appear with the text "Drag here to unload and unzip" - release the .zip there. Once that unzips your site content should then be placed (and you can check it here by clicking Site folder, then wwwroot to see site contents. You should also now be able to browse your site at YourSiteName.azurewebsites.net.

If you also need to complete a hybrid connection setup (i.e. setting up the Hybrid Connection agent in your network), let me know. Otherwise all the configuration for the app service site (including things like virtual directories) would have been set during the site creation and just that step of moving the content should have been remaining.

**Comment by scooter133** [comment]
I am using Version 1.0.6
I am running into the same issue.   Here is a Link of a video where the screen goes blank. 
https://www.screencast.com/t/JIRi1J4IwMG

Happens at about 1:15

I've let it sit for hours after that, hit enter, ESC, nothing does anything. 
the Zipfile is Created, the Zip file is about 600MB

the SCM procedure above with the debug console does not seem to be an option for me. I do not see a "Debug Console"
When I'm in the App Service I am able to get to some command line and there is only the Quickstart.html file in the directory. I do not know how to get the Zip file in there.

**Comment by krolson** [comment]
Thank you, @scooter133 - this was useful information. We have determined where this issue is happening and are working on a fix. In the meantime, there is the workaround described above for manually dropping the .zip of the site content. Could you describe a bit more about what you do see when you go to the .scm site?
When you get to the ".scm" site you should see something like this, with the Debug Console drop down options:
![20200909DebugConsoleDropdown](https://user-images.githubusercontent.com/4675080/92663445-2cee3600-f2b6-11ea-9b82-ad4c128788f5.jpg)

Then after selecting one when on the list of the file contents, you can select a file from file explorer and drag it over the file list in the browser - this should make the blue square highlighting happen, at which point dropping the file will start the upload.
![20200909DebugConsoleZipDrag](https://user-images.githubusercontent.com/4675080/92663479-45f6e700-f2b6-11ea-803b-e64ebd352657.jpg)

Are you able to get to these views or are you blocked in a different way? Note that once you drop the file there it will likely take a while to sync. 

Alternatively, you could also use FTP for manually migrating the site content (but this wouldn't take the pre-zipped site content and would require you to locate the site source content path(s)): https://docs.microsoft.com/en-us/azure/app-service/deploy-ftp

**Comment by krolson** [comment]
This issue should be fixed in the current 1.0.8 Preview release available on appmigration.microsoft.com. Please try this version and let us know if you are still experiencing this issue.
