### ISSUE TITLE
Session 293ff55f-ccfc-4b23-b0f9-3428fd9450ba. CONNECTION STRING CHECKS: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by chatremblay** [Azure/App-Service-Migration-Assistant#35]
#### Investigative information
Please provide the following:

- UTC Timestamp:   2020-08-28  
- Migration Tool App version :  1.0.6
- OS Version:  Microsoft Windows server 2016  10.0.14393 build 14393

#### Repro steps

1. Start the tool locally on the internal server
2. select the web app , then everything looks ok, other than that message 

We're sorry, there has been an error. To get help, please use the Help > Report Issues menu option and include the following information: Session 293ff55f-ccfc-4b23-b0f9-3428fd9450ba. CONNECTION STRING CHECKS: Object reference not set to an instance of an object.

![image](https://user-images.githubusercontent.com/45394319/91559709-92c9dd80-e906-11ea-9bfc-520631ed4eac.png)

#### Expected behavior

How can i fix this problem?

**Comment by chatremblay** [comment]
We are using an oracle database ,  maybe this is the issue

**Comment by krolson** [comment]
Hello @chatremblay - thank you for reporting this issue. We have opened a bug to track this issue for next release, however this won't immediately help you. There may be 2 options to work around this: (a) temporarily remove the connectionStrings section from web.config files and re-try using the tool, if the error goes away you may complete the migration and re-add the connections strings back post-migration on the migrated site (such as using the Development Tools > App Service Editor feature to edit content files in portal management view). (b) Manually migrate the site content as the tool would do (if your site uses virtual directories or if you are planning to set up a hybrid connection, then option (a) might be a better first choice, since the UI will handle more of those things and below steps do not include them). The basics of the approach are:

1.	Create a new web app in the azure portal (portal.azure.com)
2.	Create a .zip of the site content using the iisConfigAssistant.exe (like: iisConfigAssistant.exe GetZippedSiteContent "[siteName]" "[zip file location]", example: iisConfigAssistant.exe GetZippedSiteContent "Default Web Site" "C:\temp\Default Web Site.zip"). (See [here ](https://github.com/Azure/App-Service-Migration-Assistant/wiki/How-the-Assistant-Works#what-information-is-sent-for-assessments) for more on where to find iisConfigAssistant.)
3.	Go to the "scm" for the site you created during the migration: YourSiteName.scm.azurewebsites.net
4.	Click on "Debug Console" and choose either the CMD or PowerShell option to get to the file content view
5.	You should see 2 folders listed: "LogFiles" and "Site". Drag the .zip file from step (2) over the folders list in the browser and a blue square should appear with the text "Drag here to unload and unzip" - release the .zip there. Once that unzips your site content should then be placed (and you can check it here by clicking Site folder, then wwwroot to see site contents. You should also now be able to browse your site at YourSiteName.azurewebsites.net.

Please let us know if you encounter any issues using these workarounds.

**Comment by krolson** [comment]
This should no longer be a blocker for you in the Preview 1.0.8 release posted today on appmigration.microsoft.com. Please let us know if you still have similar issues using that version, and thank you for reporting this.
