### ISSUE TITLE
AppService Migration Assistant displays empty white page during migration

### ISSUE THREAD

**Issue by artisticcheese** [Azure/App-Service-Migration-Assistant#39]
#### Investigative information

Please provide the following:

- UTC Timestamp: 11:03 PM
- Migration Tool App version : 1.0.6
- OS Version: Windows 2012 R2

#### Repro steps

I assume it's not easily reproducible and specific to my system. After I started migration it's switches to image below after around 10% 

#### Expected behavior

Shall show progress/error etc

#### Actual behavior

Showing screen like below
![image](https://user-images.githubusercontent.com/13176884/94210123-8dbf6600-fe93-11ea-8c77-75ed845c67ce.png)
Portal is stuck at 10%.
![image](https://user-images.githubusercontent.com/13176884/94210182-af205200-fe93-11ea-9dd9-d2e3220263bf.png)

**Comment by krolson** [comment]
Hi @artisticcheese  - thanks for posting this! This looks a lot like the issue that was reported in this thread: https://github.com/Azure/App-Service-Migration-Assistant/issues/31 - we just closed it because it was fixed in the latest 1.0.8 preview release (available on appmigration.microsoft.com) but perhaps we should leave an issue open for a bit so it's more visible when people come to this page. Please try using the 1.0.8 build and let us know if that doesn't work for you! (note: or if you'd rather not and this is just for a single site, you can also do the manual drag-and-drop of the created .zip to your created azure site as detailed in the linked issue thread).

**Comment by artisticcheese** [comment]
New version worked
