### ISSUE TITLE
Is it possible to assess a individual application under default website in IIS.

### ISSUE THREAD

**Issue by prasanadas** [Azure/App-Service-Migration-Assistant#41]
#### Investigative information

Please provide the following:

- UTC Timestamp:
- Migration Tool App version :
- OS Version:

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

**Comment by krolson** [comment]
Unfortunately the Migration Assistant only evaluates sites as defined by IIS, not applications (i.e. which could be at any nested level), and I know also that it blocks sites using multiple application pools. This is because doing a similar type of multiple different application pool settings on the destination may not be possible in App Service, and such applications may need to be split into separate applications there. The rationale for blocking on scenarios that require large changes like this is to have such changes be made and tested locally before changing to a new environment (App Service), but we do take this as feedback for an allow-it-anyway option. 

Probably the simplest way to work around this limitation would be to create a new temporary site in IIS that uses that sub-app and it's associated application pool as it's content directory and app pool and then run the tool against that new site.
Depending on the configuration, you might also consider (in a copy of the site for avoiding breaking your current version) converting the applications to use the same application pool as the parent Default Web Site, or even changing them to simple virtual directories just to do the quick move into App Service so you can test it out there.
