### ISSUE TITLE
Cannot see the details of the assessment report on the portal

### ISSUE THREAD

**Issue by arseyam** [Azure/App-Service-Migration-Assistant#43]
After uploading the assessment report to the Azure migrate project, we are not able to view the  details of the report especially the migration blockers and warnings.

It's needed to view the data on Azure to share it with the dev team who need to work on fixing those blockers.

![Screenshot 2020-10-14 093336](https://user-images.githubusercontent.com/16021754/95952339-90f9a200-0e00-11eb-9bbc-8b4f465d8a05.png)

**Comment by krolson** [comment]
Hello @arseyam - thank you for letting us know that you would like to see this information. You are correct that, unfortunately, you cannot view this information today in the portal.azure.com view. We are keeping this feedback in mind for how to improve this current portal view.

The list of which specific checks were failed (Blockers) is present in the backend and as a workaround can be queried for directly using Azure CLI, using below steps. I will note that even using the CLI option only the names of the checks that failed will be listed, not the specific check detail messages. This is because the specific failed check message might contain sensitive information and as such today do not leave the server machine - today the only option for saving that specific message information is to Save the report to a file when running the assessment.

To start, here is a link for Azure CLI if you do not currently have it installed: https://docs.microsoft.com/en-us/cli/azure/
After installing it and running an "az login" to log in to your azure account, you can then do a GET request on the migrate project webapp data, like this (replacing the relevant subscriptionId, ResourceGroupName, and AzureMigrateProjectName fields with the ones relevant to your migrate project):

`az rest --method get --uri "https://management.azure.com/subscriptions/[subscriptionId>/resourceGroups/[ResourceGroupName]/providers/Microsoft.Migrate/MigrateProjects/[AzureMigrateProjectName]/WebSites?api-version=2020-05-01"`

You can pipe the results to a file - it should be json output with a collection of information for each site, like below - I've bolded some relevant fields for emphasis like "errorList" which is the list of the blocking checks:

{
  "nextLink": null,
  "value": [
    {
      "id": "/subscriptions/555daa41-d0b8-4d2b-965f-23ba5fd585ae/resourceGroups/MigrationHubProject/providers/Microsoft.Migrate/MigrateProjects/MyMigrationProject/WebSites/3eb2eba8-24b2-4acd-9711-5ea7cba70c54",
      "name": "3eb2eba8-24b2-4acd-9711-5ea7cba70c54",
      "properties": {
        "assessmentData": [
          {
            "assessmentId": "879e44ef-c241-4511-877f-d472b39ddec8",
            "assessmentTargetType": "Azure app service",
            "enqueueTime": "4/17/2020 9:38:58 PM",
            **"errorList": [
              "TcpPortCheck",
              "LocationTagCheck",
              "VirtualDirectoryCheck",
              "ConfigErrorCheck"
            ],**
            "extendedInfo": {
              "clientid": "55558148-6302-460e-5ac9-c0b82ac73cbf",
              "sessionid": "879e44ef-c241-4511-877f-d472b39ddec8"
            },
            "framework": null,
            "frameworkVersion": null,
            "isReadyForMigration": false,
            "lastUpdatedTime": "2020-04-17T21:38:58.328Z",
            **"migrationBlockersCount": 4,**
            "port": 443,
            "solutionName": "WebApplications-Assessment-AppServiceMigrationAssistant",
            "successList": [
              "IsapiFilterCheck",
              "GlobalModuleCheck",
              "ProtocolCheck",
              "AppPoolCheck",
              "AuthTypeCheck",
              "PhpCompatCheck",
              "ContentSizeCheck",
              "AppPoolIdentityCheck"
            ],
            **"warningList": [
              "HttpsBindingCheck"
            ],**
            **"webServerId": "server1.foo.com",**
            "webServerType": "IIS",
            **"webSiteName": "Default Web Site"**
          },
          { [...]
