### ISSUE TITLE
The following unsupported global filters were detected: WSMan

### ISSUE THREAD

**Issue by eolver** [Azure/App-Service-Migration-Assistant#50]
When Running IIS to App Migration tool on server I am getting an error for global filters check..

#### Investigative information

Please provide the following:

- UTC Timestamp: 10:07PM 4/1/21
- Migration Tool App version : 1.0.8
- OS Version: Windows Server 2012 R2

#### Repro steps

Provide the steps required to reproduce the problem:

1. Run App Migration Assessment

#### Expected behavior

 - After complete assessment expect to be able to migrate

#### Actual behavior

When run i get an error preventing migration but cannot find enough detail to resolve the error

Exported report details for failed check:

"CheckPassed": false,
            "CheckName": "GlobalModuleCheck",
            "DisplayMessage": "The following unsupported global filters were detected: WSMan",
            "Status": "Block",
            "DisplayTitle": "Global Modules",
            "CheckDescription": "Checks for global modules not standard in App Service.",
            "MoreInfoLink": "https://go.microsoft.com/fwlink/?linkid=2100816",
            "logFriendlyMessage": "The following unsupported global filters were detected: WSMan"

**Comment by krolson** [comment]
Hi @eolver 

This is happening because the "WSMan" module isn't in the explicit list of modules that we check for having corresponding Azure App Service equivalents and as such it might not work to migrate an application using it. The way to avoid that check failing would be to remove the module from IIS configuration globally (i.e. from globalModules section in applicationHost.config), or to side-step Migration Assistant and instead manually move the application content into an app service site (both ideas explained in a bit more detail in responses on this issue related to the same check but for "AppWarmupModule" rather than "WSMan": https://github.com/Azure/App-Service-Migration-Assistant/issues/45). 

We are considering ways to make it easier to work around this kind of failed check (i.e. without having to modify the global module settings for the whole server).

**Comment by eolver** [comment]
@krolson thanks for the info. Although I cannot find an applicationhost.config file to remove this.

**Comment by krolson** [comment]
The applicationHost.config file should be located in a location like %systemdrive%\Windows\System32\inetsrv\config\applicationHost.config. Note that this is one of the global configuration files that powers IIS on the machine, and changes to it can break IIS (i.e. for all the sites on the server at once), so please be careful and follow best practices like making a backup before making any changes. It is possible that at least one site on the server actually uses the WSMan module and will stop working after it's removal.

**Comment by krolson** [comment]
We are looking at options to enable working around this kind of check failure (including the ability to migrate even when errors are identified: https://github.com/Azure/App-Service-Migration-Assistant/issues/26), in the meantime please use the options noted above either to remove the global module configuration or to manually create a new site and deploy the site content as outlined in #45.
