### ISSUE TITLE
A site cannot be evaluated by App-Service-Migration-Assistant-site

### ISSUE THREAD

**Issue by ShugoYoko** [Azure/App-Service-Migration-Assistant#51]
Can the site with the following configurations be evaluated using "https://appmigratation.microsoft.com/"?

OS : Red Hat Enterprise Linux (Azure VM)
LB/Web Server : Apache,mod_jk
AP Server : OpenJDK , Tomcat
DB Server : PostgreSQL etc

#### Investigative information

- UTC Timestamp: 2021/1/13 2:00
- Migration Tool App version : n/a
- OS Version: n/a

#### Repro steps

1. Access "https://appmigratation.microsoft.com/".
2. Enter "https://mig-apgw.japaneast.cloudapp.azure.com/terasoluna-tourreservation-web/". 

Now this site is stopped. If it is necessary to start the site for your verification, please contact us.

#### Expected behavior

After I perform step 2, the following message is output.
"Your site's framework and hosting model is fully supported for migrating over to Azure App Services. Start your migration process by downloading the migration assistant and following the steps to migrate your app."

#### Actual behavior

After I perform step 2, the following message is output.
"Cannot find any information for the site. Please try another site."

#### Known workarounds

We could not find the workaround,

**Comment by krolson** [comment]
The appmigration.microsoft.com assessment works by looking at cached web-crawler type information on a given site which is periodically collected. If the site is not a publicly browsable site that has been running continuously for some time, there will not be information about it for the assessment to use for comparisons. 

That said, the online assessment will tell you about if the same frameworks are running on App Service sites today, and your description of the site sounds like something that could run as an app service site as well, so you would most likely get the Expected behavior message. This tells you it is possible to run the frameworks the site is using on App Service, however it may also be true that there would be configuration/other changes needed.

For Tomcat sites you can look at this document: https://docs.microsoft.com/en-us/azure/developer/java/migration/migrate-tomcat-to-tomcat-app-service for determining issues with running the application as an App Service site and migrating - you may be able to use the Linux Preview version of the Migration Assistant to assess the site, but only a subset of the items called out in the document are checked for automatically in that tool. The document is geared a little more for when you are planning to migrate the site by migrating code (i.e. creating an App Service Java site and then copying a .war file) as opposed to another option of creating a Docker container of your application and deploying the Docker container to App Service. Depending on how the database is currently set up you might have to migrate it as well (unless it is already in a location that is accessible by the application from app service).

**Comment by ShugoYoko** [comment]
krolson,

Thank you for your information! I understand it.
