### ISSUE TITLE
 We're sorry, there has been an error. To get help, please use the Help > Report Issues menu option and include the following information: Session d5673be7-f770-4a3f-9fc4-37dadb6ba693. Failed request to assessment endpoint with status code 403

### ISSUE THREAD

**Issue by shannuvijaya** [Azure/App-Service-Migration-Assistant#55]
#### Investigative information

Please provide the following:

- UTC Timestamp:
- Migration Tool App version :
- OS Version:

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

**Comment by krolson** [comment]
Hi @shannuvijaya - thank you for letting us know this happened. I haven't yet been able to reproduce the behavior, so this may be something specific to your setup that I'm not matching. I have also confirmed that other requests to the endpoint do appear to be getting through even very close to that time period, so the endpoint does not appear to have been down (or not for long). Does there happen to be any particular network intermediaries that might block or adjust requests between your client machine and the internet? Does browsing https://readinessapi.trafficmanager.net/ yourself from the machine also return a 403? I ask since I don't see the logs that would indicate the request made it all the way to the assessment site.

**Comment by krolson** [comment]
An alternative option now also would be to try using the PowerShell scripts that were recently released - these do not require outbound connectivity to do the assessment step (and will assess all sites on the server at once) - the scripts are a lightweight option that involves simply dropping a directory of scripts on the machine (or at least a machine-accessible location) in order to try it out.

Main info page: https://github.com/Azure/App-Service-Migration-Assistant/wiki/PowerShell-Scripts
Place to download: https://azure.microsoft.com/en-us/services/app-service/migration-assistant/
