### ISSUE TITLE
The tool hangs while migrating

### ISSUE THREAD

**Issue by viveksundararaj** [Azure/App-Service-Migration-Assistant#56]
**Investigative information**

- UTC Timestamp: September 5, 2021 11:10:00 AM
- Migration Tool App version : 1.0.6.20061101
- OS Version: Windows Server 2016

**Repro steps**

Just run the Azure App Service Migration Assistant Tool. During the assessment, the tool found 2 gave 2 warnings only. 

**Expected behavior**

An Azure WebApp must be provisioned and the content of the on premise website must be moved to Azure WebApp. 

**Actual behavior**

A new Azure WebApp is being provisioned but the content of the on premise website is not being moved to Azure WebApp. The tool hangs during the migration of web content and a blank screen appears. 

![image](https://user-images.githubusercontent.com/89717365/132145825-e89338b4-e2b9-4fc8-935f-d0a797bf4e4d.png)
![image](https://user-images.githubusercontent.com/89717365/132145830-cf24b216-8232-402d-bd70-9bcb52bcdbdf.png)

**Comment by krolson** [comment]
Hi @viveksundararaj, thank you for letting us know about this. This sounds like an issue that was fixed in the currently available Preview version of the tool. Would you be willing to try that version and let us know if that works? It would be the "App Service migration assistant for Java on Apache Tomcat (Windows—preview)" on https://azure.microsoft.com/en-us/services/app-service/migration-assistant/ - this includes the IIS app migration experience in addition to the Preview TOMCAT app option. 

If that doesn't resolve the issue, would you be willing to share a detail like the site name you used for the migration so we could try to associate backend logs for the particular site migration and see if we can tell what happened from that? You could even create a "throwaway" site just for the migration attempt.
