### ISSUE TITLE
Unhandled Exception: Choose a site

### ISSUE THREAD

**Issue by zeeshan97** [Azure/App-Service-Migration-Assistant#6]
#### Investigative information

Please provide the following:

- UTC Timestamp: 11:45 PM
- Migration Tool App version :
- OS Version: Windows 2008 R2 SP1

#### Repro steps

Provide the steps required to reproduce the problem:
Installed the tool and tried to run but getting the error message on the first screen.

![image](https://user-images.githubusercontent.com/35285000/56003268-b0979380-5c7a-11e9-8f72-ccd98bd083be.png)

Unhandled Exception: System.ArgumentException: An item with the same key has already been added. Key: sharepoint web services\c:\program files\microsoft office servers\14.0\webservices\shared\accessdataserver
 at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
 at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
 at migcheck.BuildApplicationMap.InitializePathToApplicationMapper(Site Site) in D:\a\1\s\src\MigrationTool\migcheck\BuildApplicationMap.cs:line 22
 at migcheck.BuildSiteMap.InitializeSite(Site Site) in D:\a\1\s\src\MigrationTool\migcheck\BuildSiteMap.cs:line 148
 at migcheck.BuildServerMap.InitializeServerMap() in D:\a\1\s\src\MigrationTool\migcheck\BuildServerMap.cs:line 67
 at migcheck.Program.Main(String[] args) in D:\a\1\s\src\MigrationTool\migcheck\Program.cs:line 123

**Comment by krolson** [comment]
This may be due to multiple applications pointing to the same physical path, as explained in more detail in this comment:
https://github.com/Azure/App-Service-Migration-Tool/issues/3#issuecomment-474005747 
Could you please let us know if you think that is not the case for your server? We are looking at long term solutions to this type of case to not only improve this error experience but to actually enable you to still do a migration, but don't have a timeline for this yet.

**Comment by NitashaV** [comment]
We have released a [new Preview version](https://appmigration.microsoft.com/readiness) of Migration Assistant today that should help address this class of issues. We would appreciate if you gave this update (in Preview) a try and let us know if this works for your scenario. Thanks

**Comment by Frontarolli** [comment]
I got the same error here:
**TypeError: Cannot read property 'split' of undefined**

The server I'm running the Migration Assistant has 12 applications.
Is there any workaround?
Thanks.

**Comment by krolson** [comment]
Hello @Frontarolli 
This is due to a dependency on .NET Framework 4.7.2. We are fixing this error message to be more actionable (as well as making it more clear on the Migration Assistant page that this is a requirement). The way to work around this is to install .NET framework 4.7.2 runtime on the machine (such as from here: https://support.microsoft.com/en-us/help/4054530/microsoft-net-framework-4-7-2-offline-installer-for-windows). 
Apologies for the inconvenience,
Kristina
