### ISSUE TITLE
(PowerShell) Get-SiteReadiness.ps1 returning a false positive outcome

### ISSUE THREAD

**Issue by samaea** [Azure/App-Service-Migration-Assistant#61]
Even though migration warnings are displayed when running .\Get-SiteReadiness.ps1 that will prevent migration on Site X, it still states "Site X _No Blocking issues found and the site is ready for migration to Azure!_"

#### Investigative information

Please provide the following:

- UTC Timestamp: 14/01/2022 01:31
- Migration Tool App version : Latest.
- OS Version: Win Server 2016 DC

#### Repro steps

Provide the steps required to reproduce the problem:

1. In IIS Server, I created a Website (e.g. Site X) that is on port 8080.
2. Ran the Get-SiteReadiness.ps1 script, which returns warning about the TCP Port, but also states Site X is ready for migration.

#### Expected behavior

Script should inform me the site is not ready for migration and that remediation step Y is required to resolve the issue before I am able to migrate the site to App Service. 

#### Actual behavior

Although TCP Port warnings are displayed, it states "Site X _No Blocking issues found and the site is ready for migration to Azure!_"

![image](https://user-images.githubusercontent.com/32162601/149436602-a8455fbc-29a1-4881-8669-11d83e417d5b.png)

#### Known workarounds

N/A

**Comment by krolson** [comment]
Hi @samaea,

Thank you for letting us know this doesn't seem right - I can see how that looks a little funny. The reason for this behavior is that we consider some checks to be "warning" level and not "blocking" - so while the site has an identified warning for the TcpPortCheck, we don't consider that to be a blocker for going ahead and trying out the migration and no other (Blocking) checks failed.  

Specifically the TcpPortCheck looks at the bindings and whether the app is configured to receive traffic on ports other than 80 and 443. On App Service side incoming HTTP traffic will only be allowed on these 2 ports. The app may still be migrated without making code or configuration changes. Clients making requests to the new App Service site would have to specify the app service site URL without the less-standard ports, so we definitely still want you to be aware that this is something that would be different between the local IIS and App Service versions of the site since it might require changes to clients of the site.

**Comment by samaea** [comment]
I think the confusion came from the UI version of the tool which does not allow you to proceed with the migration upon that warning being thrown (if I recall correctly). Thanks for the clarity Krolson!
