### ISSUE TITLE
Issue assessing public Url- stuck fetshing data

### ISSUE THREAD

**Issue by jporrata** [Azure/App-Service-Migration-Assistant#7]
We are having issues assessing public URLS through https://appmigration.microsoft.com/.  The tool gat stuck fetching data of this sites.

https://ociteapps.suagm.edu/sica/
https://ociteapps.suagm.edu/Certificacion/Default.aspx
https://ociteapps.suagm.edu/WebAdmissions/start_page.aspx#no-back-button

#### Repro steps

Provide the steps required to reproduce the problem:

**Comment by NitashaV** [comment]
Thanks for reporting this issue! we will investigate this and report back.

**Comment by NitashaV** [comment]
Thanks for reporting this issue. Online assessment tool is able to assess internet facing sites only. We did fix the bug on our end to not be stuck forever in loading. 
In order to assess an internal application, we would recommend you install Migration Assistant at https://appmigration.microsoft.com/readiness on your web server. This tool will be able to discover and assess your OnPremises IIS site to check if its ready for lift and shift to App Services.
