### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by tsaksa13** [Azure/App-Service-Migration-Assistant#71]
#### Investigative information

Please provide the following:

- UTC Timestamp: 17:57 September 7th, 2022
- Migration Tool App version : 1.0.6.20061101
- OS Version: Server 2022 (Version 21H2, OS Build 20348.887)

#### Repro steps

Provide the steps required to reproduce the problem:
1. Selected Correct Site
2. Scan began and completed.
3. 13 Success, 0 Warnings, and 0 Errors
4. A red box appears stating: We're sorry, there has been an error. To get help, please use the Help > Report Issues menu option and include the following information: Session 2f0e07a4-09b5-490f-82c9-e3ae2671436d. CONNECTION STRING CHECKS: Object reference not set to an instance of an object.
5. ![f7586c74-43c8-434c-8439-281ba5daa644](https://user-images.githubusercontent.com/1497834/188946832-c4dca62f-9f92-4b94-8640-f70bce531eb1.jpg)

#### Expected behavior

 - The "Next" Button to be clickable

#### Actual behavior
- The red box appears with the error stated above and the "Next" Button is not clickable

#### Known workarounds

- No current workarounds. Attempting to use the powershell scripts but no success thus far.

**Comment by krolson** [comment]
Hi @tsaksa13 ,

Thanks for using our Issues page! This issue should be fixed in the current Windows Preview (download called "App Service migration assistant for Java on Apache Tomcat (**Windows—preview**)" on the https://azure.microsoft.com/en-us/services/app-service/migration-tools/ page). Could you please try using that version and see if it resolves the issue for you? It's a Preview primarily for the Java Tomcat migration - the IIS app migration experience is the same (with a few bug fixes like this one). 

Thank you,
Kristina

**Comment by tsaksa13** [comment]
@krolson, that did the trick! Thanks for letting me know to get the Java on Apache Tomcat version.

**Comment by krolson** [comment]
I'm glad that worked!
