### ISSUE TITLE
Azure Webapp unable to see mount storage option when we use Azure Migration Tools

### ISSUE THREAD

**Issue by Lpatrick88** [Azure/App-Service-Migration-Assistant#76]
#### Investigative information

Please provide the following:

- UTC Timestamp:
- Migration Tool App version : 1.0.6
- OS Version: Windows Server 2019

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.
Supposedly can see mount storage option. 

#### Actual behavior

Provide a description of the actual behavior observed.

 If we create the webapp in Azure. we able to see mount storage option. 

#### Known workarounds

Provide a description of any known workarounds.

**Comment by krolson** [comment]
Hi @Lpatrick88,
Unfortunately the Migration Assistant tool does not support a mount storage option - not all options that are available in the Azure Portal are exposed in the migration assistant. It would also be possible to manually create a site in the Azure Portal and then drop a .zip of the root site content there rather than using the Migration Assistant interface to do the end-to-end if you want more customization / options.
