### ISSUE TITLE
Error (401) Unauthorized while executing Invoke-SiteMigration.ps1 during task "Beginning zip deployment"

### ISSUE THREAD

**Issue by ASchwarz1984** [Azure/App-Service-Migration-Assistant#83]
After executing the Invoke-SiteMigration.ps1 I'm receiving error 401 Unauthorized during publishing of zip file.

#### Investigative information

Please provide the following:

- UTC Timestamp: 6/28/2023 10:30:00 AM
- Migration Tool App version: Latest PowerShell Scripts
- OS Version: Windows Server 2022

#### Repro steps

Provide the steps required to reproduce the problem:

Executing script as described here: https://github.com/Azure/App-Service-Migration-Assistant/wiki/PowerShell-Scripts
The execution of Invoke-SiteMigration.ps1 leads to an error 401 during zip publishing. All previous steps succeed.

#### Expected behavior

Provide a description of the expected behavior.

Zip content gets published.

#### Actual behavior

Provide a description of the actual behavior observed.

Zip content publishing fails

**Comment by krolson** [comment]
Hi @ASchwarz1984 - I have a first guess for why this is happening, which is that this is due to Basic Authentication being disabled on the site. Could you check if you have it disabled by looking at the site resource in Azure Portal > go to Configuration and General Settings > see what's shown for Basic Authentication (on or off).
The PowerShell scripts use basic auth with the publish profile credentials to do the content migration.

**Comment by ASchwarz1984** [comment]
Thank you @krolson. I can confirm that Basic Authentication was disabled due to Azure Policy enforcement. I've modified the script to pause after Web App creation to be able to update the web app configuration and allow basic authentication temporarily.

**Comment by krolson** [comment]
(Noting here that PowerShell scripts no longer use Basic Authentication for the content publishing step)
