### ISSUE TITLE
Missing web app site content after apparently successful migration

### ISSUE THREAD

**Issue by ASchwarz1984** [Azure/App-Service-Migration-Assistant#84]
After successfully using Azure App Service Migration Assistant no web site content is available on Azure. We are running a very simple and text only Default.htm site on IIS 10 (Windows Server 2022). However, even though the Migration Assistant reports no issues and states that the migration was successful, we are missing the content of the web site on Azure and the App Services still shows the default "Your web app is running and waiting for your content" page.

#### Investigative information

Please provide the following:

- UTC Timestamp: 2023-06-28T12:17:30
- Migration Tool App version : 1.0.6
- OS Version: Windows Server 2019 and Windows Server 2022

#### Repro steps

Provide the steps required to reproduce the problem:

1. Install IIS with sample web page using powershell
Add-WindowsFeature Web-Server -IncludeManagementTools; powershell -ExecutionPolicy Unrestricted Add-Content -Path "C:\\inetpub\\wwwroot\\Default.htm" -Value $($env:computername)
2. Download and use App Service Migration Assistant to migrate the Web Site to Azure App Service.

#### Expected behavior

Provide a description of the expected behavior.

Content on Azure App Service is the same as on the VM.

#### Actual behavior

Provide a description of the actual behavior observed.

Missing content and Default Azure App Service landing page is shown.

**Comment by ASchwarz1984** [comment]
Linked to issue #83. If Basic Authentication is disabled on the App Service then App Service Migration Assistant will not upload IIS site content.

**Comment by Yuichi-Ikeda** [comment]
#83 is only provided a workaround for PowerShell Scripts.  App Service Migration Assistant is not possible to pause migration process, so we cannot enable Basic Authentication for App Service during migration process.  And also, App Service Migration Assistant support migration app to new app service only, not support migration app to an existing app service. Therefore, we cannot use App Service Migration Assistant under Basic Authentication is forced disabled due to Azure Policy enforcement.
