### ISSUE TITLE
Azure App Service Migration Assistant fails when sending assessment data to Migrate Project

### ISSUE THREAD

**Issue by robdock92** [Azure/App-Service-Migration-Assistant#88]
#### Problem Description

Unsure if you're able to retrieve it, but I created an Azure support ticket for this, and they told me I should open an Issue here. Ticket number is 2401020040010925.

Using the App Service Migration Assistant (downloaded from [here](https://azure.microsoft.com/en-us/products/app-service/migration-tools/)), we would like to upload the assessment data gathered by the tool to our Migrate Project; however, when on the 'Azure Migrate Hub' step in the tool, the following error occurs when the 'Send assessment data' button is pressed: 

`Step error details: Error: RegisterTool error: Error: Push to Event Hub error: TypeError: Failed to fetch.` 

![image](https://github.com/Azure/App-Service-Migration-Assistant/assets/156129745/250f73d5-f6f8-42a7-bc78-2b930f6c6a75)

Our network firewall is showing that a connection is being made to readinessapi.trafficmanager.net as expected, but I'm unsure if there are other websites (beyond what is listed [here](https://github.com/Azure/App-Service-Migration-Assistant/wiki/How-the-Assistant-Works#outbound-connections)) that need to be whitelisted.

#### Investigative information

Please provide the following:

- UTC Timestamp: 2024-01-09T19:57:31Z
- Migration Tool App version :  1.0.6
- OS Version: Windows Server 2016 Standard

#### Repro steps

Provide the steps required to reproduce the problem: 

1.) Download Migration Tool App to server.
2.) Install app.
3.) Run app.
4.) Select only website listed on machine.
5.) Run assessment.
6.) Log into Azure as prompted by app.
7.) Select the "Send assessment data" button.
8.) Error occurs.

#### Expected behavior

Provide a description of the expected behavior.

- App should deliver assessment data to Azure Migrate for viewing.

#### Actual behavior

Provide a description of the actual behavior observed.

- App errors when sending assessment data.

#### Known workarounds

Provide a description of any known workarounds.

- Unknown

**Comment by robdock92** [comment]
I would try the powershell scripts as documented in the [wiki](https://github.com/Azure/App-Service-Migration-Assistant/wiki/PowerShell-Scripts), but the URL to download the scripts now redirects to a new page that doesn't contain the download (or at least that I can find).

**Comment by krolson** [comment]
Hi @robdock92 - thank you for your patience and posting about this issue here. Based on the logs from around the timestamp indicated, it looks like there may have been a timeout that occurred. Is this problem persistent and repeatable, or does sending results to Azure work sometimes or for other applications? 

Related to workarounds - yes, there are the PS scripts, the content page including the download links has recently moved, and the https://aka.ms/appmigrate link points to the new location. We have also updated the wiki page with the direct download link.

There is also the option in the App Service Migration Assistant to "Save Report" to save the results in json format in a local file (which is more detailed than what would be saved to Azure Migrate)

**Comment by robdock92** [comment]
@krolson Thank you for the reply.

Yes, the problem is persistent and repeatable across any number of servers/applications I try to utilize it with in our environment. I can see good traffic outbound from any of the servers, and I don't see any blocked traffic from our network firewall that would prevent uploading of this data.

Something I noticed with the Powershell scripts is that Azure CLI is required in order to send data to the Azure Migrate project. Is that a requirement also for the App Service Migration Assistant?

Thank you for updating the link to where the Powershell download is. I was able to utilize it to get the site readiness report and package up the results.

I found the Save Report button earlier, and it works to give us the information we need to move forward. I'm okay with closing this issue out unless you'd like to try troubleshooting the upload process. If so, let me know how I can best help.

**Comment by krolson** [comment]
Hi @robdock92 - I am glad those other options are working for you, and thank you for letting us know.

The AzureCLI is not a requirement for the App Service Migration Assistant(ASMA) - ASMA should be effectively self-contained.

Based on server-side telemetry, it does not look like this is a widespread issue of the upload-to-migrate-project operation failing generically, so we will close this issue for now.

I forgot to add the note above as well that the documented list of required outgoing connections is vague for those required for the Azure Migrate connections at just "Azure Migration endpoints if updating Azure Migrate Project status (Optional)" because there was not a simple consistent set of hardcoded URLs to list to make this work for everyone.
