### ISSUE TITLE
App Service Migration Assistant tool "Azure Migrate Hub" Issue

### ISSUE THREAD

**Issue by DevallaSubbu** [Azure/App-Service-Migration-Assistant#97]
We need some help on App Service Migration Assistant tool [Home · Azure/App-Service-Migration-Assistant Wiki · GitHub](https://github.com/Azure/App-Service-Migration-Assistant/wiki) . When I get into below step it is not loading anything even though we created Azure Migrate project or create new from below. This is for .net Web site converting IaaS to PaaS (web app)..

![Image](https://github.com/user-attachments/assets/f273e0b1-4d7f-4286-9179-a982af996156)

**Comment by DevallaSubbu** [comment]
Adding more details, we have similat application on multiple Azure VM (windows 2019) whenever we ran above tool it went all the way to "Login to Azure" step from there is not moving. We have installed edge and make default . Also we were able to open portal from same azure VM. We have cut a tikcet to Microssft they said they are not suportng this tool..lol

**Comment by krolson** [comment]
Couple questions on this: 

1. What version of the tool is this (will be visible in the "Help" drop down) - 1.0.6? 1.0.8? Notably if this is the 1.0.6 version, there were some changes to this page in the 1.0.8 version that may affect this behavior (though I am unable to replicate this using either version) but which also might log more information. (1.0.8 is the "[App Service migration assistant for Java on Apache Tomcat (Windows—preview)](https://appmigration.microsoft.com/api/download/windows/AppServiceMigrationAssistant.msi)" version on https://aka.ms/appmigrate - the Java part is preview, but it also contains some bug fixes for the IIS apps discovery as well)
2. Does anything else not work that you've noticed (specifically if you skip this step to add an Azure Migrate project, do Azure Options show you results for subscriptions, resource groups, etc. to choose from or are these also blank)? (I understand this might be difficult to check if you only have blocked sites, but if you have one that doesn't have any blockers...)
3. Are you selecting any non-default "select a different cloud" or different directory options during login/on the page? 

Taking a step back: is the goal for this tool to migrate a few sites / evaluate a bunch of sites? I'm wondering if there might be another option here to accomplish something similar if this is not working, especially given that this particular step would save only minimal information to the Azure Migrate project. There may be some alternate option like saving the report from this tool, using PS scripts to generate the reports / migrate, using Azure Migrate directly, bulk VM assessment with scripts (https://github.com/Azure/App-Service-Migration-Assistant/tree/master/AzureVmAssessmentFeature) etc. - it's quite possible that doing the site migration may fail with the GUI due to current App Service defaults (GUI doesn't support migration without using Basic Auth, where PS scripts do, for example)).

**Comment by DevallaSubbu** [comment]
Version I'm using 1.0.6.

If skip "Azure Migrate Project" I can't go to further steps but it is
showing as option like "pick next project" which we don't want....Or else
it is going step 1 again("Choose Stie")

No

*Thank you*



*Best Regards,*

*Subbu Devalla*

*425 615 9567*

**Comment by DevallaSubbu** [comment]
When i click on preview version i'm still 1.0.6 version which is weird

*Thank you*



*Best Regards,*

*Subbu Devalla*

*425 615 9567*

**Comment by krolson** [comment]
Apologies - looks like the link is incorrect for the Preview version - it should be this one for 1.0.8: https://appmigration.microsoft.com/api/download/windowspreview/AppServiceMigrationAssistant.msi

**Comment by DevallaSubbu** [comment]
Now it is working. Thank you.

*Thank you*



*Best Regards,*

*Subbu Devalla*

*425 615 9567*
